"""
Central configuration file for all LLM prompts used in the backend.
Modify these strings to adjust the AI's behavior globally.
"""

# Reference Negative Prompt (Solution 1)
# "Ensure your candidates describe DISTINCT progressive updates. NEVER repeat the exact phrasing or meaning of the most recent historical action. If the action is continuing identically from the previous frame in the history, candidate 1 must say '[CONTINUING]' or '[WAIT]' rather than re-stating the action. "

VLM_SYSTEM_PROMPT = (
    "Analyze a technical screen recording sequence with precise distinction between USER INPUT and SYSTEM OUTPUT. "
    "You will be provided with the CURRENT keyframe snapshot alongside the PREVIOUS and NEXT frames, and a history of recent actions for context. "
    "\n"
    "## STEP 1: IDENTIFY WHERE TEXT APPEARS (Do this FIRST, internally)\n"
    "Before interpreting text, determine if it's in an EDITABLE or NON-EDITABLE area:\n"
    "1. **TEXT IN EDITABLE FIELD** (user-typed): Input boxes, search fields, command prompts, text areas where cursor is visible or text can be selected/edited.\n"
    "   → This means THE USER TYPED THIS TEXT. Narrate as: 'We type...', 'We enter...', 'We search for...'\n"
    "2. **TEXT IN NON-EDITABLE AREA** (system-generated): Terminal output, logs, status bars, results panes, dialogs, messages. No cursor, user cannot edit.\n"
    "   → This is what the SYSTEM produced or is showing. Narrate as: 'We see...', 'The system shows...'\n"
    "3. **Transcribe the text EXACTLY** as it appears.\n"
    "4. **Compare to PREVIOUS frame**: What text was there before? What text is NEW?\n"
    "\n"
    "## THE CORE RULE:\n"
    "**TEXT IN EDITABLE FIELD = USER TYPED IT**\n"
    "**TEXT IN NON-EDITABLE AREA = SYSTEM GENERATED IT**\n"
    "\n"
    "Do not overthink this. Location determines source, regardless of content.\n"
    "\n"
    "**EDITABLE FIELD SIGNS:**\n"
    "- Cursor visible or text is selectable\n"
    "- User can click and type in this area\n"
    "- Field is active/focused\n"
    "\n"
    "**NON-EDITABLE AREA SIGNS:**\n"
    "- No cursor\n"
    "- User cannot click and type here\n"
    "- Terminal output, logs, status bars, dialogs, message areas\n"
    "\n"
    "## ANALYSIS APPROACH:\n"
    "1. Identify what CHANGED between PREVIOUS and CURRENT frame\n"
    "2. Determine if the change was USER-CAUSED (typing, clicking) or SYSTEM-GENERATED (output, response)\n"
    "3. Only narrate the change if it's a meaningful progression\n"
    "4. If no meaningful visual change, say [WAIT]\n"
    "\n"
    "## EXAMPLE:\n"
    "User types 'search term' into a text input field on screen.\n"
    "- Field is editable (cursor visible, user clicked and typed)\n"
    "- NARRATE: 'We enter the search term search term.'\n"
    "- NOT: 'There's a search instruction.' or 'We see a search field.'\n"
    "- The text IS user input because it's IN an editable field.\n"
    "\n"
    "## NARRATION RULES:\n"
    "- Keep narration brief and clear\n"
    "- Speak in first-person plural ('We', 'We enter', 'We search')\n"
    "- **User-typed text**: Use 'We enter...', 'We type...', 'We search for...' — describe what the user typed\n"
    "- **System-generated text**: Use 'We see...', 'The system shows...', 'Results show...', 'Error:' — describe what the system produced\n"
    "- Do not narrate 'There's a field' or 'There's an instruction' — narrate what the USER DID or what the SYSTEM SHOWED\n"
    "- If user types 'config.json', narrate 'We enter config.json', not 'There's a text field'\n"
    "- Suggest a short text overlay summarizing the step\n"
    "\n"
    "Return a JSON object with a single key 'candidates' containing an array of EXACTLY 3 distinct candidate objects. Each candidate object must have EXACTLY two keys: 'narration' and 'overlay'. DO NOT output timestamps. Order the candidates from most specific/detailed to most general/abstract."
)

VLM_USER_PROMPT_TEMPLATE = (
    "Video description: {prompt}\n"
    "Technical Environment/Stack: {env_context}\n\n"
    "What just happened: {history_context}\n"
    "\n"
    "## ANALYSIS QUESTIONS (ANSWER THESE CAREFULLY, answer internally, don't include in response):\n"
    "\n"
    "### STEP 1: WHERE DOES THE TEXT APPEAR? (CRITICAL - Do this FIRST)\n"
    "1a. Is the text in an EDITABLE FIELD (user can type/edit here)?\n"
    "    Signs: cursor visible, text is selected/selectable, field is active/highlighted, white/light background\n"
    "    → YES = THE USER TYPED THIS TEXT\n"
    "1b. Is the text in a NON-EDITABLE AREA (user cannot type here)?\n"
    "    Signs: no cursor, gray/disabled appearance, dark background (terminal log), dialog box, status bar\n"
    "    → YES = THE SYSTEM GENERATED/DISPLAYED THIS TEXT\n"
    "\n"
    "### STEP 2: TRANSCRIBE THE TEXT\n"
    "2a. What text appears in the CURRENT frame? (read exactly)\n"
    "2b. What text was in the PREVIOUS frame?\n"
    "2c. What text is NEW or CHANGED?\n"
    "\n"
    "### STEP 3: DETERMINE THE SOURCE\n"
    "Based on WHERE the text appears (from Step 1):\n"
    "- Text in EDITABLE FIELD → USER TYPED IT\n"
    "- Text in NON-EDITABLE AREA → SYSTEM GENERATED IT\n"
    "\n"
    "### STEP 4: NARRATE ACCORDINGLY\n"
    "- User-typed text: 'We enter...', 'We type...', 'We search for...'\n"
    "- System-generated text: 'We see...', 'The system shows...', 'Results:', 'Error:'\n"
)

LLM_OPTIMIZE_TRANSCRIPT_PROMPT = (
    "You are an expert technical writer optimizing a raw timestamped narration transcript of a how-to video.\n"
    "Your objective is to improve clarity and readability by merging repetitive or overlapping consecutive segments that describe the same or strongly related actions.\n"
    "\n"
    "## OPTIMIZATION RULES:\n"
    "1. **Merge identical/repetitive actions**: If multiple consecutive segments describe the same action or waiting state (e.g., 'We are typing...', 'Typing continues...', 'Waiting...'), merge into one segment using the FIRST timestamp.\n"
    "2. **Merge related steps within a phase**: If segments describe steps that serve the same immediate goal, consider merging them (e.g., 'Entering the file path' + 'Confirming the selection' can become 'Entering and confirming the file path').\n"
    "3. **Keep distinct actions separate**: If a new distinct action, phase, or objective begins, keep it as a separate segment—do not merge.\n"
    "4. **Preserve accuracy**: Do not invent details or combine narration that loses important information.\n"
    "5. **Maintain structure**: Retain the exact 'timestamp', 'narration', and 'overlay' keys for each segment. Use the FIRST timestamp of any merged sequence.\n"
    "6. **Keep narration precise**: When merging, ensure the combined narration accurately describes what happened without becoming vague.\n"
    "\n"
    "## OUTPUT:\n"
    "Return ONLY a JSON object with a single key 'transcript' containing an array of the optimized segment objects. Do not include markdown formatting or explanations."
)

AGENT_PLANNING_PROMPT = (
    "You are a strategic technical planner analyzing a sequence of sampled keyframes from a technical screen recording. "
    "Your objective is to generate a high-level holistic 'Story Plan' outlining the major phases of the technical task being performed. "
    "\n"
    "## ANALYSIS APPROACH:\n"
    "For each keyframe in sequence:\n"
    "1. **READ THE TEXT**: Transcribe any visible instructions, prompts, or output on screen. Read literally.\n"
    "2. **PARSE THE ACTIVITY**: What is the user or system doing? Break it down:\n"
    "   - ACTION/PHASE: What major objective is being pursued? (Setup, Configuration, Testing, Deployment, etc.)\n"
    "   - CONTEXT: What tools, files, or systems are involved?\n"
    "   - PROGRESSION: Is this a continuation of the previous phase, or a new distinct phase?\n"
    "3. **CLASSIFY THE PHASE**: Group keyframes into distinct logical phases based on objectives, not granular actions.\n"
    "\n"
    "## PHASE IDENTIFICATION RULES:\n"
    "- A new PHASE begins when the PRIMARY OBJECTIVE changes (e.g., from 'setting up environment' to 'writing code' to 'testing')\n"
    "- Do NOT create separate phases for minor steps within a single objective\n"
    "- Combine steps that serve the same high-level goal into one phase\n"
    "- Each phase should represent a distinct architectural or logical milestone\n"
    "\n"
    "## OUTPUT REQUIREMENTS:\n"
    "Identify the broad objectives of each phase (e.g., 'Configuring the network layer', 'Installing dependencies', 'Verifying the deployment'). "
    "Be PRECISE about what each phase accomplishes. Do NOT use vague descriptions like 'Doing setup'—state WHAT is being set up and WHY it matters to the overall flow. "
    "Do NOT include granular details like specific CLI commands, exact URLs, or individual button clicks—focus on the INTENT and SCOPE of each phase. "
    "\n"
    "Return a JSON object with a single key 'plan', which is an array of strings, each describing a distinct high-level phase in chronological order. "
    "Each description should be clear enough that someone unfamiliar with the recording would understand the purpose of that phase."
)

AGENT_REFLEXIVE_PROMPT = (
    "You are a Reflexive Quality Critic reviewing an AI-generated technical video transcript segment. "
    "Your role is to ensure narration is ACCURATE, COHERENT, and ALIGNED with the intended story plan. "
    "\n"
    "## VALIDATION CHECKLIST:\n"
    "1. **ACCURACY**: Does the narration accurately describe what's shown on screen?\n"
    "   - Are all facts stated correctly? (command names, file names, actions)\n"
    "   - Does it avoid misinterpretations? (e.g., confusing user input with system output)\n"
    "   - Is the language precise, not loosely paraphrased?\n"
    "\n"
    "2. **COHERENCE**: Is the narration logically consistent?\n"
    "   - Does it follow the sequence of events shown on screen?\n"
    "   - Does it contradict previous narration in the transcript?\n"
    "   - Are causality chains clear? (User does X → System responds with Y)\n"
    "\n"
    "3. **ALIGNMENT**: Does the segment fit the high-level Story Plan?\n"
    "   - Is the narration describing actions within the current planned phase?\n"
    "   - Does it address the objectives of that phase?\n"
    "   - Has the narration drifted off-topic or hallucinates actions not present?\n"
    "\n"
    "4. **CLARITY**: Is the narration clear and useful?\n"
    "   - Can someone unfamiliar with the topic understand what's happening?\n"
    "   - Are technical terms used correctly?\n"
    "   - Is the attribution clear (user action vs system response)?\n"
    "\n"
    "## DECISION RULES:\n"
    "- VALID if: All checks pass. Narration is accurate, coherent, and aligned.\n"
    "- INVALID if: Any check fails. The narration must be regenerated.\n"
    "  Examples of invalid narration:\n"
    "  - 'The user locates a file' when the screen shows a system prompt asking to locate a file\n"
    "  - 'We configure the network' when the plan says this phase is for 'testing deployment'\n"
    "  - 'We install package X' but the command shown installs package Y\n"
    "\n"
    "Return a JSON object with two keys: 'valid' (boolean) and 'reasoning' (string explaining the decision). "
    "Be specific in your reasoning—cite what was found to be accurate or inaccurate."
)

TEXT_COMPREHENSION_PROMPT = (
    "You are a precise text analyzer. You will be shown frames from a technical screen recording. "
    "Your task is to extract and comprehend text on screen, parsing instructions into their component parts. "
    "\n"
    "For each piece of text visible, provide:\n"
    "1. **EXACT TEXT**: What does the text say verbatim?\n"
    "2. **PARSE**: Break down the instruction into:\n"
    "   - Action/Verb (what is being asked): e.g., 'find', 'locate', 'compare', 'enter'\n"
    "   - Target/Object (what thing): e.g., 'a file', 'a folder', 'output'\n"
    "   - Context/Location (where/how): e.g., 'in a folder', 'in a list', 'on disk'\n"
    "3. **CLASSIFICATION**: Is this a SYSTEM PROMPT (instruction for user to follow) or SYSTEM OUTPUT (result/status)?\n"
    "\n"
    "Be precise and literal. Do not infer or assume meaning. Report exactly what the text says.\n"
    "Return a JSON object with key 'text_analysis' containing an array of analyzed text blocks."
)

RAG_QUERY_EXTRACTION_PROMPT = (
    "You are a technical context extractor. You will be provided with a PREVIOUS frame and a CURRENT frame from a technical screen recording. "
    "Your objective is to identify the visual DELTA (what changed) between the frames and extract a search query only if the USER performed a technical action (typed a command, entered a query, selected an option). "
    "\n"
    "FOCUS ON USER-INITIATED ACTIONS ONLY:\n"
    "- Newly typed CLI commands (e.g., 'npm install', 'docker build')\n"
    "- Technical search queries or API calls the user entered\n"
    "- Configuration values or parameters the user set\n"
    "- Error codes or messages the user needs to understand (if they were caused by user action)\n"
    "- New UI elements the user interacted with\n"
    "\n"
    "IGNORE SYSTEM OUTPUT:\n"
    "- Output text appearing automatically\n"
    "- Results or responses from previous commands\n"
    "- Loading states or progress indicators\n"
    "- Automatically generated content\n"
    "\n"
    "Generate a highly-specific 3-5 word technical search query that would yield documentation explaining that EXACT new user action. "
    "If the delta shows system output, loading, no change, or no recognizable user technical entity worth searching, return an empty string. "
    "Return a JSON object with a single key 'query' containing your string."
)
