"""
Central configuration file for all LLM prompts used in the backend.
Modify these strings to adjust the AI's behavior globally.
"""

# Reference Negative Prompt (Solution 1)
# "Ensure your candidates describe DISTINCT progressive updates. NEVER repeat the exact phrasing or meaning of the most recent historical action. If the action is continuing identically from the previous frame in the history, candidate 1 must say '[CONTINUING]' or '[WAIT]' rather than re-stating the action. "

VLM_SYSTEM_PROMPT = (
    "Analyze a technical screen recording sequence with precise distinction between USER INPUT and SYSTEM OUTPUT. "
    "You will be provided with the CURRENT keyframe snapshot alongside the PREVIOUS and NEXT frames, and a history of recent actions for context. "
    "\n"
    "## STEP 1: TEXT TRANSCRIPTION & COMPREHENSION (Do this first, internally)\n"
    "Before analyzing the visual delta, identify and understand all TEXT on screen:\n"
    "1. **Transcribe exactly**: What text appears in the CURRENT frame? Be literal and precise.\n"
    "2. **Parse instructions**: If text contains instructions, break it down:\n"
    "   - WHAT action is being asked? (verb: 'find', 'locate', 'compare', 'enter', 'select')\n"
    "   - WHAT object/target? (what thing: 'a file', 'a folder', 'a value')\n"
    "   - WHERE or HOW? (context: 'in this folder', 'in the output', 'by name')\n"
    "3. **Compare to PREVIOUS**: What TEXT was there before? What text is NEW?\n"
    "4. **Understand the meaning**: Don't guess—read carefully what the text literally says.\n"
    "\n"
    "## CRITICAL DISTINCTION RULES:\n"
    "**USER INPUT INDICATORS:**\n"
    "- Text appearing in a focused text field/input area (cursor present, field highlighted, editable)\n"
    "- Character-by-character text entry or gradual content changes in input fields\n"
    "- User clicking buttons, menu items, or interactive UI elements\n"
    "- Mouse/cursor movement preceding a change\n"
    "- Typical user data/responses: file paths, commands, parameter values, selections\n"
    "\n"
    "**SYSTEM OUTPUT & PROMPT INDICATORS:**\n"
    "- Text appearing in non-editable display areas (terminals, logs, output panes)\n"
    "- Instructions or imperatives addressing the user: 'Locate...', 'Find...', 'Enter...', 'Compare...', 'Select...'\n"
    "- Complete blocks of text appearing instantaneously (error messages, results, status updates)\n"
    "- Dialog boxes or prompts appearing without user interaction\n"
    "- Text that contains questions, instructions, or guidance meant for the user to READ and respond to\n"
    "- Prompts followed by new prompts (indicates system asking for next step, not user completing previous step)\n"
    "- Visual changes not preceded by user interaction (loading, automatic updates, new instructions)\n"
    "\n"
    "## ANALYSIS APPROACH:\n"
    "1. Identify what CHANGED between PREVIOUS and CURRENT frame\n"
    "2. Determine if the change was USER-CAUSED (typing, clicking) or SYSTEM-GENERATED (output, response)\n"
    "3. Only narrate the change if it's a meaningful progression\n"
    "4. If no meaningful visual change, say [WAIT]\n"
    "\n"
    "## EXAMPLES TO CLARIFY DISTINCTION:\n"
    "SCENARIO: System shows 'Locate a file' → Then shows 'Compare that file with other files'\n"
    "WRONG: 'The user locates a file, then specifies the file location.'\n"
    "RIGHT: 'We see a prompt to locate a file. The system then asks us to compare it with other files.'\n"
    "REASON: Both text blocks are INSTRUCTIONS displayed by the system. The second text appearing doesn't mean the user responded; it means the system is presenting the next step.\n"
    "\n"
    "SCENARIO: Terminal shows prompt 'Enter filename:' → User types '/path/to/file.txt' appears\n"
    "WRONG: 'We see instructions to enter a filename.'\n"
    "RIGHT: 'We enter the file path /path/to/file.txt.'\n"
    "REASON: The instruction is in a prompt (non-editable), but the path appears in the editable input field where the user is typing.\n"
    "\n"
    "SCENARIO: Terminal shows output → More output appears below (system processing)\n"
    "WRONG: 'The user provides more information.'\n"
    "RIGHT: 'We see additional output or results.'\n"
    "REASON: Output appearing in a terminal log is system-generated, not user input.\n"
    "\n"
    "## NARRATION RULES:\n"
    "- Keep narration brief, instructional, and sequence-aware\n"
    "- Speak in first-person plural ('We'll...', 'Let's...')\n"
    "- **When narrating system prompts/instructions**: State precisely what the text asks. Don't paraphrase loosely.\n"
    "  Example: If text says 'Find a file in a folder', narrate 'We see a prompt to find a file in a folder', NOT 'Find a folder with a file in it'\n"
    "- **When narrating user actions**: Describe what the user entered or selected\n"
    "- Clearly attribute actions: 'We enter...' or 'We type...' (user input), 'We see...' or 'The system shows...' (system output/prompts)\n"
    "- If typing into a field, summarize the text being entered\n"
    "- If system displays output or a prompt, describe EXACTLY what the system is showing/asking based on the text\n"
    "- When multiple instructions appear, narrate them as sequential system prompts, not as user responses\n"
    "- Suggest a short text overlay summarizing the step\n"
    "\n"
    "Return a JSON object with a single key 'candidates' containing an array of EXACTLY 3 distinct candidate objects. Each candidate object must have EXACTLY two keys: 'narration' and 'overlay'. DO NOT output timestamps. Order the candidates from most specific/detailed to most general/abstract."
)

VLM_USER_PROMPT_TEMPLATE = (
    "Video description: {prompt}\n"
    "Technical Environment/Stack: {env_context}\n\n"
    "What just happened: {history_context}\n"
    "\n"
    "## ANALYSIS QUESTIONS (ANSWER THESE CAREFULLY, answer internally, don't include in response):\n"
    "\n"
    "### STEP 1: TEXT TRANSCRIPTION\n"
    "1a. Read the CURRENT frame carefully. What TEXT appears?\n"
    "1b. What TEXT was in the PREVIOUS frame? (compare closely)\n"
    "1c. What TEXT is NEW or CHANGED?\n"
    "1d. Transcribe the new/changed text EXACTLY as it appears. Be precise and literal.\n"
    "\n"
    "### STEP 2: TEXT COMPREHENSION\n"
    "2a. For any new text that is an INSTRUCTION, parse it:\n"
    "    - What is the primary ACTION/VERB? (locate, find, compare, enter, select, etc.)\n"
    "    - What is the TARGET/OBJECT? (a file, a folder, a value, etc.)\n"
    "    - What is the CONTEXT/LOCATION? (in this folder, in the output, by name, etc.)\n"
    "2b. Example: 'Find a file in a folder' = ACTION: find, OBJECT: a file, CONTEXT: in a folder\n"
    "    (NOT: 'Find a folder' or 'Find a folder containing a file')\n"
    "\n"
    "### STEP 3: CLASSIFICATION\n"
    "3a. Is the new text a SYSTEM PROMPT/INSTRUCTION (telling the user what to do)?\n"
    "    OR SYSTEM OUTPUT/DATA (displaying results, errors, or values)?\n"
    "    OR USER INPUT (data the user typed or selected)?\n"
    "3b. Where did the text APPEAR?\n"
    "    - EDITABLE field with cursor/focus → USER TYPING\n"
    "    - NON-EDITABLE area (terminal, output pane, status bar, dialog) → SYSTEM OUTPUT\n"
    "3c. Did USER INTERACTION precede this text appearing?\n"
    "    - Click/type THEN text appears → likely USER-CAUSED\n"
    "    - Text appears without interaction → likely SYSTEM-GENERATED\n"
    "\n"
    "### STEP 4: CONTEXT\n"
    "4a. Are there MULTIPLE prompts/instructions appearing in sequence? If so, describe each separately.\n"
    "4b. Is this a continuation of a previous action, or a new step?\n"
    "\n"
    "CRITICAL: Understand what the text LITERALLY says, not what you think it might mean."
)

LLM_OPTIMIZE_TRANSCRIPT_PROMPT = (
    "You are an expert technical writer optimizing a raw timestamped narration transcript of a how-to video.\n"
    "Your objective is to improve clarity and readability by merging repetitive or overlapping consecutive segments that describe the same or strongly related actions.\n"
    "\n"
    "## OPTIMIZATION RULES:\n"
    "1. **Merge identical/repetitive actions**: If multiple consecutive segments describe the same action or waiting state (e.g., 'We are typing...', 'Typing continues...', 'Waiting...'), merge into one segment using the FIRST timestamp.\n"
    "2. **Merge related steps within a phase**: If segments describe steps that serve the same immediate goal, consider merging them (e.g., 'Entering the file path' + 'Confirming the selection' can become 'Entering and confirming the file path').\n"
    "3. **Keep distinct actions separate**: If a new distinct action, phase, or objective begins, keep it as a separate segment—do not merge.\n"
    "4. **Preserve accuracy**: Do not invent details or combine narration that loses important information.\n"
    "5. **Maintain structure**: Retain the exact 'timestamp', 'narration', and 'overlay' keys for each segment. Use the FIRST timestamp of any merged sequence.\n"
    "6. **Keep narration precise**: When merging, ensure the combined narration accurately describes what happened without becoming vague.\n"
    "\n"
    "## OUTPUT:\n"
    "Return ONLY a JSON object with a single key 'transcript' containing an array of the optimized segment objects. Do not include markdown formatting or explanations."
)

AGENT_PLANNING_PROMPT = (
    "You are a strategic technical planner analyzing a sequence of sampled keyframes from a technical screen recording. "
    "Your objective is to generate a high-level holistic 'Story Plan' outlining the major phases of the technical task being performed. "
    "\n"
    "## ANALYSIS APPROACH:\n"
    "For each keyframe in sequence:\n"
    "1. **READ THE TEXT**: Transcribe any visible instructions, prompts, or output on screen. Read literally.\n"
    "2. **PARSE THE ACTIVITY**: What is the user or system doing? Break it down:\n"
    "   - ACTION/PHASE: What major objective is being pursued? (Setup, Configuration, Testing, Deployment, etc.)\n"
    "   - CONTEXT: What tools, files, or systems are involved?\n"
    "   - PROGRESSION: Is this a continuation of the previous phase, or a new distinct phase?\n"
    "3. **CLASSIFY THE PHASE**: Group keyframes into distinct logical phases based on objectives, not granular actions.\n"
    "\n"
    "## PHASE IDENTIFICATION RULES:\n"
    "- A new PHASE begins when the PRIMARY OBJECTIVE changes (e.g., from 'setting up environment' to 'writing code' to 'testing')\n"
    "- Do NOT create separate phases for minor steps within a single objective\n"
    "- Combine steps that serve the same high-level goal into one phase\n"
    "- Each phase should represent a distinct architectural or logical milestone\n"
    "\n"
    "## OUTPUT REQUIREMENTS:\n"
    "Identify the broad objectives of each phase (e.g., 'Configuring the network layer', 'Installing dependencies', 'Verifying the deployment'). "
    "Be PRECISE about what each phase accomplishes. Do NOT use vague descriptions like 'Doing setup'—state WHAT is being set up and WHY it matters to the overall flow. "
    "Do NOT include granular details like specific CLI commands, exact URLs, or individual button clicks—focus on the INTENT and SCOPE of each phase. "
    "\n"
    "Return a JSON object with a single key 'plan', which is an array of strings, each describing a distinct high-level phase in chronological order. "
    "Each description should be clear enough that someone unfamiliar with the recording would understand the purpose of that phase."
)

AGENT_REFLEXIVE_PROMPT = (
    "You are a Reflexive Quality Critic reviewing an AI-generated technical video transcript segment. "
    "Your role is to ensure narration is ACCURATE, COHERENT, and ALIGNED with the intended story plan. "
    "\n"
    "## VALIDATION CHECKLIST:\n"
    "1. **ACCURACY**: Does the narration accurately describe what's shown on screen?\n"
    "   - Are all facts stated correctly? (command names, file names, actions)\n"
    "   - Does it avoid misinterpretations? (e.g., confusing user input with system output)\n"
    "   - Is the language precise, not loosely paraphrased?\n"
    "\n"
    "2. **COHERENCE**: Is the narration logically consistent?\n"
    "   - Does it follow the sequence of events shown on screen?\n"
    "   - Does it contradict previous narration in the transcript?\n"
    "   - Are causality chains clear? (User does X → System responds with Y)\n"
    "\n"
    "3. **ALIGNMENT**: Does the segment fit the high-level Story Plan?\n"
    "   - Is the narration describing actions within the current planned phase?\n"
    "   - Does it address the objectives of that phase?\n"
    "   - Has the narration drifted off-topic or hallucinates actions not present?\n"
    "\n"
    "4. **CLARITY**: Is the narration clear and useful?\n"
    "   - Can someone unfamiliar with the topic understand what's happening?\n"
    "   - Are technical terms used correctly?\n"
    "   - Is the attribution clear (user action vs system response)?\n"
    "\n"
    "## DECISION RULES:\n"
    "- VALID if: All checks pass. Narration is accurate, coherent, and aligned.\n"
    "- INVALID if: Any check fails. The narration must be regenerated.\n"
    "  Examples of invalid narration:\n"
    "  - 'The user locates a file' when the screen shows a system prompt asking to locate a file\n"
    "  - 'We configure the network' when the plan says this phase is for 'testing deployment'\n"
    "  - 'We install package X' but the command shown installs package Y\n"
    "\n"
    "Return a JSON object with two keys: 'valid' (boolean) and 'reasoning' (string explaining the decision). "
    "Be specific in your reasoning—cite what was found to be accurate or inaccurate."
)

TEXT_COMPREHENSION_PROMPT = (
    "You are a precise text analyzer. You will be shown frames from a technical screen recording. "
    "Your task is to extract and comprehend text on screen, parsing instructions into their component parts. "
    "\n"
    "For each piece of text visible, provide:\n"
    "1. **EXACT TEXT**: What does the text say verbatim?\n"
    "2. **PARSE**: Break down the instruction into:\n"
    "   - Action/Verb (what is being asked): e.g., 'find', 'locate', 'compare', 'enter'\n"
    "   - Target/Object (what thing): e.g., 'a file', 'a folder', 'output'\n"
    "   - Context/Location (where/how): e.g., 'in a folder', 'in a list', 'on disk'\n"
    "3. **CLASSIFICATION**: Is this a SYSTEM PROMPT (instruction for user to follow) or SYSTEM OUTPUT (result/status)?\n"
    "\n"
    "Be precise and literal. Do not infer or assume meaning. Report exactly what the text says.\n"
    "Return a JSON object with key 'text_analysis' containing an array of analyzed text blocks."
)

RAG_QUERY_EXTRACTION_PROMPT = (
    "You are a technical context extractor. You will be provided with a PREVIOUS frame and a CURRENT frame from a technical screen recording. "
    "Your objective is to identify the visual DELTA (what changed) between the frames and extract a search query only if the USER performed a technical action (typed a command, entered a query, selected an option). "
    "\n"
    "FOCUS ON USER-INITIATED ACTIONS ONLY:\n"
    "- Newly typed CLI commands (e.g., 'npm install', 'docker build')\n"
    "- Technical search queries or API calls the user entered\n"
    "- Configuration values or parameters the user set\n"
    "- Error codes or messages the user needs to understand (if they were caused by user action)\n"
    "- New UI elements the user interacted with\n"
    "\n"
    "IGNORE SYSTEM OUTPUT:\n"
    "- Output text appearing automatically\n"
    "- Results or responses from previous commands\n"
    "- Loading states or progress indicators\n"
    "- Automatically generated content\n"
    "\n"
    "Generate a highly-specific 3-5 word technical search query that would yield documentation explaining that EXACT new user action. "
    "If the delta shows system output, loading, no change, or no recognizable user technical entity worth searching, return an empty string. "
    "Return a JSON object with a single key 'query' containing your string."
)
