apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspaces-pvc
  namespace: unmuted
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
